FORMAT: 1A
HOST: http://st15api-test.nflc.umd.edu

# ST15 API
ST15 API is the api for the redesigned Startalk system.

# Group Proposals
All services related to the proposal submission process.

## Proposals Collection [/proposals]
### List all Proposals [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "proposal one"
        }, {
          "id": 2, "title": "proposal two"
        }]

### Create a new Proposal [POST]
+ Request (application/json)

        { "title": "My Test Proposal" }

+ Response 201 (application/json)

        { "id": 3, "title": "My Test Proposal" }

## Proposal [/proposals/{id}]
A single Proposal object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Proposal to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "My Example Proposal title." }

### Remove a Proposal [DELETE]
+ Response 204


## Budgets Collection [/budgets]
### List all Budgets [GET]
+ Response 200 (application/json)

        [{
          "id": 1, 
          "title": "Jogging in park"
        }, {
          "id": 2, 
          "title": "Pick-up posters from post-office"
        }]

### Create a Budget [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/budgets/{id}]
A single proposal Budget object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the budget. Has example value.

### Retrieve a Budget [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Budget [DELETE]
+ Response 204


# Group Programs
All services related to the programs submission process.

## Programs Collection [/programs]
### List all Programs [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "program one"
        }, {
          "id": 2, "title": "program two"
        }]

### Create a new Program [POST]
+ Request (application/json)

        { "title": "My Test Program" }

+ Response 201 (application/json)

        { "id": 3, "title": "My Test Program" }

## Programs [/programs/{id}]
A single Programs object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Proposal to perform action with. Has example value.

### Retrieve a Projgram [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "My Example Program title." }

### Remove a Program [DELETE]
+ Response 204




